export const ALL_EMPLOYEES: string[] = [
  'Admir Bocerri',
  'Alfonso Allende',
  'Ardit Arifi',
  'Arijan Qollaku',
  'Berivan Coban',
  'Besmira Jahija',
  'Destan Celik',
  'Dion Maliqi',
  'Endrit Beadini',
  'Erand Vinca',
  'Feim Sahiti',
  'Fjolla Shaqiri',
  'Idriz Ajeti',
  'Imran Hamzic',
  'Isra Daljipi',
  'Leart Ajeti',
  'Metin Beadini',
  'Milad Ahmadyar',
  'Nuhi Cerkini',
  'Riza Ahmeti',
];
